name: KeepDay
main: com.flaviozno.keepday.KeepDay
version: 1.2
api-version: 1.20
commands:
  keepdaytoggle:
    description: Toggle day progress messages
    usage: /keepdaytoggle
    permission: keepday.toggle
permissions:
  keepday.toggle:
    default: op
