name: Release Plugin

on:
  push:
    branches:
      - main

jobs:
  use-template:
    uses: jerobas/.github/.github/workflows/update-readme.yml@main
    secrets: inherit

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build plugin with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Create GitHub Release with JAR
        run: |
          version=$(grep "^version:" src/main/resources/plugin.yml | awk '{print $2}')
          tag="v$version"
          name="KeepDay $tag"

          gh release create "$tag" --title "$name" --notes "Release $name" build/libs/*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
