name: Release Plugin

on:
    push:
        branches:
            - main

jobs: 
    use-template:
      uses: jerobas/.github/.github/workflows/update-readme.yml@main
      secrets: inherit
     
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create GitHub Release with JAR
              run: |
                version=$(grep "^version:" plugin.yml | awk '{print $2}')
                tag="v$version"
                name="KeepDay v$version"

                git tag "$tag"
                git push origin "$tag"

                gh release create "$tag" --title "$name" --notes "Release $name" build/libs/*.jar
              env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
              shell: bash
